name: Create site artifact

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - uses: actions/cache@v1
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      - name: Jekyll Action
        uses: lemonarc/jekyll-action@1.0.0

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.3.1
        with:
          name: build
          path: ./_site/
          if-no-files-found: error

